### ISSUE TITLE
Is there something broken with v6.0.1?

### ISSUE THREAD

**Issue by erocheleau** [salesforce/sfdx-lwc-jest#402]
### I tried to update to @salesforce/sfdx-lwc-jest@winter25 and that resolves to 6.0.1

But when I try to run my tests, a lot of them fail with 

`TypeError: specificMockImpl.apply is not a function`

Specifically around the lines where my components would call imperative Apex, that I am mocking with Jest following the pattern in the documentation by Salesforce:

```
jest.mock(
  '@salesforce/apex/ControllerName.functionName',
  () => {
    return {
      default: jest.fn(),
    };
  },
  { virtual: true },
);

// And then using something like this in my tests:
functionName.mockImplementation(...);
```

They all seem to fail with v6.0.1, but they pass no problem if I update to Spring25 or v7.0.0.

#### Steps to Reproduce

Try to have a component calling an Apex imperative controller method, and mock it using Jest for your tests, the test will fail with the error:

`TypeError: specificMockImpl.apply is not a function` and point to the line where you call the imperative Apex method in your component's code.

#### Expected Results

Expected to be able to mock the Apex call using Jest.fn like before.

#### Actual Results

`TypeError: specificMockImpl.apply is not a function` error is thrown.

### Version

-   @salesforce/sfdx-lwc-jest: 6.0.1
-   Node: v20.16.0

**Possible Solution**

Upgrade to v7.0.0,
However it seems to me that we're upgrading to what's not yet released with Spring25 instead of testing on current Winter25

Example:
![image](https://github.com/user-attachments/assets/72eb4971-849b-473b-95a0-568d1a1d9d0f)

**Comment by nolanlawson** [comment]
This seems like a duplicate of https://github.com/salesforce/sfdx-lwc-jest/issues/397

I guess since 6.x corresponds to Winter '25 and 7.x corresponds to Spring '25, we need a patch release for Winter '25.

**Comment by nolanlawson** [comment]
Fixed in 6.0.2: https://github.com/salesforce/sfdx-lwc-jest/releases/tag/v6.0.2

**Comment by erocheleau** [comment]
Totally missed that issue, I think because it was already closed!

Thank you the quick turn around on this,

I just tried it with 6.0.2 and I am still getting the errors :( 

Anything else I can help with other than installing `@salesforce/sfdx-lwc-jest@6.0.2` and re-running the tests?

With 7.0.0 or 7.0.1 my tests are still passing

I don't know if it matters but the version of @lwc/engine-dom seems to differ between what is requested by `@salesforce/sfdx-lwc-jest` and what is requested by other dependencies like `@lwc/jest-preset` ?

![image](https://github.com/user-attachments/assets/82561fa7-84be-447a-867c-6a84e243dd63)

**Comment by nolanlawson** [comment]
I'm surprised you are getting the same error since the Jest mock change (https://github.com/salesforce/lwc-test/pull/260) came in `@lwc/jest-*` [16.1.0](https://github.com/salesforce/lwc-test/releases/tag/v16.1.0) and you have 16.0.3.

Are you getting the same exact error? Can you do `npm ls @lwc/jest-preset` and `npm ls @lwc/jest-transformer` to ensure you are getting 16.0.3 consistently?

As for `@lwc/engine-dom`, yes you should ideally have the same version everywhere. If you want to test Winter '24 then the version should be 7.1.5. (I just realized you have 7.2.6 because we accidentally used a `^` instead of a `~`, but I can fix that separately and it shouldn't be a big difference.)

**Comment by erocheleau** [comment]
I have 

```
└─┬ @salesforce/sfdx-lwc-jest@6.0.2
       └── @lwc/jest-preset@16.0.3
```
and
```
└─┬ @salesforce/sfdx-lwc-jest@6.0.2
       ├─┬ @lwc/jest-preset@16.0.3
        │    └── @lwc/jest-transformer@16.0.3 deduped
       └── @lwc/jest-transformer@16.0.3 
```
Which looks to be the versions you set with your changes to 6.0.2 right? I checked to see that everything was matching after I updated to 6.0.2

**Comment by nolanlawson** [comment]
In that case I am stumped. Could you try manually installing different versions of `@lwc/jest-*` to see which one breaks your tests? E.g. you should be able to use [npm overrides](https://docs.npmjs.com/cli/v10/configuring-npm/package-json?v=true#overrides) to specify a certain version.

**Comment by erocheleau** [comment]
> In that case I am stumped. Could you try manually installing different versions of `@lwc/jest-*` to see which one breaks your tests? E.g. you should be able to use [npm overrides](https://docs.npmjs.com/cli/v10/configuring-npm/package-json?v=true#overrides) to specify a certain version.

Will do :) 

Any specific version to start with? :D that you have a feeling would work?
If I take the versions for what is set in the 7.0.1 version directly would that break anything?

I am assuming that all the versions of `@lwc/jest-*` need to be the same right?

These four? (These are the versions of those packages used in 7.0.1 so I can try those?

```
        "@lwc/jest-preset": "^18.1.1",
        "@lwc/jest-resolver": "^18.1.1",
        "@lwc/jest-serializer": "^18.1.1",
        "@lwc/jest-transformer": "^18.1.1",
```

**Comment by nolanlawson** [comment]
Correct. Those four should have the same version.

There have been a lot of changes to `@lwc/jest-*` recently so I'm not sure which one exactly broke you. 🙂  I'd recommend a [bisect-style](https://git-scm.com/docs/git-bisect) approach.

**Comment by erocheleau** [comment]
> Correct. Those four should have the same version.
> 
> There have been a lot of changes to `@lwc/jest-*` recently so I'm not sure which one exactly broke you. 🙂 I'd recommend a [bisect-style](https://git-scm.com/docs/git-bisect) approach.

Is there any reason not to simply use the versions 18.1.1 which seem to work with 7.0.1? Do these packages relate to the "expected" LWC engine that is different between Winter25 and Spring25 for example? (I don't know if 18.1.1 works yet, just want to understand the relation between the @lwc/jest packages and the lwc engines/versions of Salesforce releases)

**Comment by nolanlawson** [comment]
You can certainly do that; it's just that we try to pair the "expect" `lwc/jest-*` packages with their corresponding `lwc/*` packages. Right now those are the version combos that Salesforce is using internally. But conceptually the two are minimally coupled, so you can typically mix and match whatever version you want.
